version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: realestate-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Skatextremepro1
      MONGO_INITDB_DATABASE: real_state
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - realestate-network

volumes:
  mongodb_data:

networks:
  realestate-network:
    driver: bridge
